@file:Suppress("PackageDirectoryMismatch")

object Versions {

    const val gradleVersion = "7.1.2"
    const val kotlinVersion = "1.6.10"
    const val coreKtxVersion = "1.7.0"
    const val appCompatVersion = "1.4.1"
    const val materialVersion = "1.5.0"
    const val junit4Version = "4.13.2"
    const val junitExtensionsVersion = "1.1.3"
    const val espressoCoreVersion = "3.4.0"
    const val daggerHiltVersion = "2.41"
    const val composeNavigationVersion = "2.4.1"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "4.9.3"
    const val moshiVersion = "1.13.0"
    const val mpAndroidChartVersion = "3.1.0"
    const val lottieVersion = "5.0.3"
    const val truthVersion = "1.1.3"
    const val mockkVersion = "1.12.3"
    const val robolectricVersion = "4.7.3"
    const val androidArchCoreTest = "2.1.0"
    const val coroutinesVersion = "1.6.0"
    const val ktlintVersion = "0.40.0"
    const val gradleVersionsPluginVersion = "0.42.0"
    const val composeVersion = "1.1.1"
    const val composeActivityVersion = "1.4.0"
    const val composeViewModelVersion = "2.4.1"
    const val kotlinCompilerExtensionVersion = "1.1.1"
    const val composeConstraintLayoutVersion = "1.0.0"
    const val hiltNavigationCompose = "1.0.0"
    const val accompanistSwipeRefresh = "0.23.1"
    const val roomVersion = "2.4.2"
    const val glance = "1.0.0-alpha01"
}
