@file:Suppress("PackageDirectoryMismatch")

object Versions {

    const val gradleVersion = "7.0.0"
    const val kotlinVersion = "1.5.31"
    const val coreKtxVersion = "1.6.0"
    const val appCompatVersion = "1.3.1"
    const val materialVersion = "1.4.0"
    const val constraintLayoutVersion = "2.1.1"
    const val swipeRefreshLayoutVersion = "1.1.0"
    const val junit4Version = "4.13.2"
    const val junitExtensionsVersion = "1.1.3"
    const val espressoCoreVersion = "3.4.0"
    const val daggerHiltVersion = "2.39.1"
    const val composeNavigationVersion = "2.4.0-beta01"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "4.9.2"
    const val moshiVersion = "1.12.0"
    const val mpAndroidChartVersion = "3.1.0"
    const val lottieVersion = "4.2.0"
    const val truthVersion = "1.1.3"
    const val mockkVersion = "1.12.0"
    const val robolectricVersion = "4.6.1"
    const val androidArchCoreTest = "2.1.0"
    const val coroutinesVersion = "1.5.2"
    const val ktlintVersion = "0.40.0"
    const val gradleVersionsPluginVersion = "0.39.0"
    const val composeVersion = "1.0.4"
    const val composeActivityVersion = "1.3.1"
    const val composeViewModelVersion = "2.4.0-rc01"
    const val kotlinCompilerExtensionVersion = "1.1.0-alpha06"
    const val composeConstraintLayoutVersion = "1.0.0-beta02"
    const val hiltNavigationCompose = "1.0.0-alpha03"
    const val accompanistSwipeRefresh = "0.21.0-beta"
}
